version: 0.2

env:
  secrets-manager:
    GITLAB_TOKEN: GitLabToken

phases:
  pre_build:
    commands:
      - echo Checking out "${GIT_BRANCH}" from repository "${GIT_URL}"...
      # This always builds the head of the branch regardless of what the GIT_COMMIT is.
      - git clone --branch "${GIT_BRANCH}" --no-checkout "${GIT_URL/:\/\//://oauth2:${GITLAB_TOKEN}@}" src
      - git checkout "${GIT_COMMIT}"
      - cd src
  build:
    commands:
      - echo Build started on `date`
      - echo Building...
      - bin/build.sh
  post_build:
    commands:
      - echo Build completed on `date`
